### PR TITLE
Updated windows clients

### PR DESCRIPTION
**Pull request by poVoq**
Added Gajim with link to Windows store and added Movim (&logo) with link to server selection page.

### CODE REVIEW

**Comment by mwild1** [comment]
Does this commit intentionally remove converse.js?

**Comment by poVoq** [comment]
I think it makes sense to have a curated list of clients and not overload list, and I have seen too many people use the test version on ConverseJS.org as if it was Discord or so, so I don't think that is something that should be promoted.

**Comment by poVoq** [comment]
> Converse has Electron and Tauri apps for Windows iirc



> Converse has Electron and Tauri apps for Windows iirc

An argument could be made to link directly to that and remove UWXP since it is abandoned.

**Comment by poVoq** [comment]
The merge-conflict is not fixable here in the github interface as apparently I can't remove files and I don't have my system setup to directly access github git repos.

Can you just force merge it? It is only the same Movim.svg that somehow got merged in another PR.

**Comment by mwild1** [comment]
Can you review #69 instead? I've changed the way client metadata is managed and how client display is configured.

**Pull request closed without merging**
